# Generated by Django 2.0.5 on 2018-05-25 06:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('date_of_birth', models.DateField()),
                ('first_name', models.CharField(max_length=100, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last_name')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.PositiveSmallIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)], verbose_name='order_number')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'waiting'), (1, 'preparation'), (2, 'ready'), (3, 'delivered'), (4, 'canceled')], verbose_name='status')),
                ('consume_location', models.PositiveSmallIntegerField(choices=[(0, 'take_away'), (1, 'in_shop')], verbose_name='consume_location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderCheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.PositiveSmallIntegerField(default=5000)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_content', to='restframework.Order')),
            ],
            options={
                'verbose_name': 'OrderCheckList',
                'verbose_name_plural': 'OrderCheckList',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='name')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_content', to='restframework.Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductCustomization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customizable', models.CharField(max_length=50, verbose_name='customizable')),
                ('price', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='price')),
                ('is_available', models.BooleanField(default=True, verbose_name='is_available')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_options', to='restframework.Product')),
            ],
            options={
                'verbose_name': 'Product_customization',
                'verbose_name_plural': 'Product_customization',
            },
        ),
        migrations.AddField(
            model_name='orderchecklist',
            name='product_customization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='restframework.ProductCustomization'),
        ),
        migrations.AlterUniqueTogether(
            name='productcustomization',
            unique_together={('product', 'customizable')},
        ),
    ]
